# ----------------------------------------------------------------------
# Github Actions  configuration
#
# ----------------------------------------------------------------------
name: feature-branch-workflow

#--------------------------
# Event triggers
#--------------------------
on:
  push:
    branches:
      - feat-*
      - feat/*

#--------------------------
# jobs
#--------------------------

jobs:
  # Checkout code
  checkout-code:
    name: Checkout code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add SHORT_SHA env property with commit short sha
        id: vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          # echo "shortsha=$shortsha" >> $GITHUB_OUTPUT
          echo "GITHUB_REPOSITORY_NAME=$(basename ${{ github.repository }})" >> $GITHUB_OUTPUT

    outputs:
      SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}
      GITHUB_REPOSITORY_NAME: ${{ steps.vars.outputs.GITHUB_REPOSITORY_NAME }}

  # Build & push container image
  #-----------------------------
  build-push-container-image:
    name: Build & push container image
    runs-on: ubuntu-latest
    needs: checkout-code
    # permissions required for AWS OIDC provider
    # permissions:
    #   id-token: write
    #   contents: read

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-